navikt/familie-tilbake-frontend

src/frontend/komponenter/Fagsak/Høyremeny/Historikk/HistorikkInnslag.tsx
Funksjonalitet lagt til for å støtte design endringer i favrokort: 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12197
Legger til en styled bordy short for å få til new lines i historikk.
Gitt en slik respons fra familie-historikk:
```
{
"behandlingId": "9a2fb5c3-371d-4bd4-8cca-0d6026525376",
"eksternFagsakId": "9594918",
"fagsystem": "EF",
"applikasjon": "FAMILIE_TILBAKE",
"type": "HENDELSE",
"aktør": "SAKSBEHANDLER",
"aktørIdent": "Z994151",
"tittel": "Bruker med utenlandsk adresse er lagt til som brevmottaker",
"tekst": "Uy Nguyen\nFA 11\nHelsfyr\n0585\nOslo\nNorge",
"steg": null,
"journalpostId": null,
"dokumentId": null,
"opprettetTid": "2023-05-08T00:07:42.42"
}
```
Før:
Etter:
=> Legger til en stylized bodyshort med whitespace preline

src/frontend/komponenter/Fagsak/Brevmottaker/BrevmottakerContext.tsx
Favrokort: [NAV-12456](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12456)
Det skal ikke være mulig å velge Norge i mottagerliste dersom det er en utenlandsk adresse. Likevel kan Norge velges dersom man f.eks. velger Norge på Verge, men endrer mottager etterpå. Denne PR'en legger inn en fiks for dette slik at dersom man har valgt Norge på ulovligvis vil bruker få en feilmelding.
=> Legg inn en validering for om Norge er valgt ulovlig, og vis feilmelding

src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/Behandlingsmeny.tsx, src/frontend/typer/Brevmottaker.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12385
NAV-12385 - Samlekort 
* ref: NAV-12155 Menyrekkefølge: Menyinnlsaget "Legg til / fjern brevmottaker" bør komme nederst i menyen, likt som i BA-sak
* ref: NAV-12164 Tekstendring: Riktig radiotekst skal være: "Oppslag i personregister"
=> NAV-12385 - Samlekort (ref: NAV-12155) Menyrekkefølge: "Legg til / fjern brevmottaker" bør komme nederst i menyen.

src/frontend/komponenter/Fagsak/Brevmottaker/LeggTilEndreBrevmottakerModal.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13885
Det er lagt til støtte for feilmelding i brevmottakerskjema - for validerings-feilmelding som kommer fra backend ved oppretting av manuell brevmottaker (egen PR backend) - dersom behandlingen inneholder fortrolig person (har adresebeskyttelse: STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND)
=> NAV-13885 Lagt til feilmelding i brevmottakerskjema for validerings-feilmelding fra backend

src/frontend/context/AppContext.tsx, src/frontend/komponenter/Container.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/LeggTilFjernBrevmottakere/LeggTilFjernBrevmottakere.tsx, src/frontend/komponenter/Felleskomponenter/Toast/Toast.tsx, src/frontend/komponenter/Felleskomponenter/Toast/Toasts.tsx, src/frontend/komponenter/Felleskomponenter/Toast/typer.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-13885
* Det er lagt til funksjonalitet for toasts (samme som i ba-sak-frontend)
* Det er lagt til konkret Toast for håndtering av feilmelding relatert til valg av "Legg til brevmottaker" fra behandlingsmenyen.
Dette menyvalget oppretter trinn for å administrere manuelle brevmottakere og kan i prinsippet trigges fra ulike sider - noe som gjør det nødvendig med en "global visning" av potensiell advarsel (validerings-feilmelding) - med informasjon om at det ikke er tillatt fordi behandlingen inneholder fortrolig person.(person med adressebeskyttelse STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND).
Ettersom det er klønete å ha feilmeldingen i menyen (ev under menypunktet) da denne lukker seg i det man …
=> NAV-13885 Lagt til Toast for feilmelding ved forsøk på å legge til trinn for manuelle brevmottakere på behandling som inneholder fortrolig person

build_n_deploy/naiserator/naiserator_dev_gcp.yaml, build_n_deploy/naiserator/naiserator_prod_gcp.yaml, build_n_deploy/naiserator/naiserator_redis_default.yaml, build_n_deploy/naiserator/naiserator_redis_exporter.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjerner CPU-limit

package.json, yarn.lock
Ved oppstart lokalt (yarn start:dev) kommer følgende advarsel:
"One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
"
Fix: `yarn add @babel/plugin-proposal-private-property-in-object -D`
=> Fix for "babel-preset-react-app import: @babel/plugin-proposal-private-property-in-object"

package.json, src/frontend/komponenter/Fagsak/Brevmottaker/LeggTilEndreBrevmottakerModal.tsx, src/frontend/komponenter/Fagsak/Fakta/FaktaRevurdering.tsx, src/frontend/komponenter/Fagsak/Fakta/FaktaSkjema.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Dokumentlisting/Journalpostvisning.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Historikk/HistorikkInnslag.tsx, src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMelding.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Totrinnskontroll/Totrinnskontroll.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/EndreBehandlendeEnhet/EndreBehandlendeEnhet.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/HenleggBehandling/ForhåndsvisHenleggelsesbrev/ForhåndsvisHenleggelsesbrev.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/HenleggBehandling/HenleggBehandlingModal/HenleggBehandlingModal.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/SettBehandlingPåVent/SettBehandlingPåVent.tsx, src/frontend/komponenter/Fagsak/Verge/VergeContainer.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/Aktsomhetsvurdering/SærligeGrunnerSkjema.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx, src/frontend/komponenter/Felleskomponenter/Modal/PåVent/PåVentModal.tsx, yarn.lock
**Aksel v5 - byttet diverse form elements**
* Fjern @deprecated/unødvendig `size=“small”` fra `Detail` komponent
* Bytt diverse `FamilieSelect` (`@navikt/familie-form-elements`) med `Select` (`@navikt/ds-react`)
* Bytt diverse `FamilieTilbakeTextArea` -> `FamilieTextarea` (`@navikt/familie-form-elements`) med `Textarea` (`@navikt/ds-react`)
_Komponentene som er byttet var de som var enklest å teste - noen gjenstår - men etter merge av denne er betraktelig færre igjen._
=> Aksel v5 - byttet diverse form elements

src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.test.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.test.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/ForeldelsePeriodeSkjemaContext.tsx, src/frontend/komponenter/Fagsak/Foreldelse/typer/feilutbetalingForeldelse.ts, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/GjennoptaBehandling/GjennoptaBehandling.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/SettBehandlingPåVent/SettBehandlingPåVent.tsx, src/frontend/komponenter/Felleskomponenter/Datovelger/Datovelger.tsx, src/frontend/komponenter/Felleskomponenter/Modal/PåVent/PåVentContext.tsx, src/frontend/komponenter/Felleskomponenter/Modal/PåVent/PåVentModal.tsx, src/frontend/typer/api.ts, src/frontend/utils/dato.ts, src/frontend/utils/validering.ts
Bytter til ny DatePicker fra Aksel for alle stedene hvor vi har datovelger for skjemafelter. Etter dette mangler det kun oppgradering ett sted, men dette stedet bruker ikke Felt fra familie-skjema, og må løses på en litt annen måte. Tar det derfor i egen PR.
Koden i `Datovelger.tsx` og `dato.ts` er kopiert fra ba-sak/ks-sak. Kommer også mer opprydning i dato-funksjoner på sikt, syns derfor det var ryddig å starte på en ny og clean dato-fil som ligner på hvordan det gjøres i ba-sak og ks-sak.
Legger ved skjermbilder i kommentarer
=> Chore: Gammel datovelger til DatePicker fra Aksel

.eslintrc.json, src/frontend/komponenter/Fagsak/Fakta/FaktaRevurdering.tsx, src/frontend/komponenter/Fagsak/Fakta/FaktaSkjema.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePerioder.tsx, src/frontend/komponenter/Fagsak/Verge/VergeContainer.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.tsx, src/frontend/komponenter/Felleskomponenter/Periodeinformasjon/PeriodeOppsummering.tsx
Del 1 av denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18314
Skriver oss bort fra `nav-frontend-grid` komponenter på Verge, Fakta og Foreldelse-stegene. Tar resten i en egen PR, så det ikke blir alt for stort.
Noen steder kunne vi bare slette komponentene uten at det påvirket stylingen, mens andre steder har jeg måttet bytte det ut med primitiver fra Aksel. Syns selv koden ble mye mer lesbar!
Tror jeg ville ha lest alt i ett og ikke commit for commit. Ble litt mye endringer på en komponent, men det er total diff jeg tror er best å lese. Legger ved skjermbilder til hver fil. Noen steder ser det ut som flere endringer fordi jeg har flyttet litt på hvor ulike komponenter ligger, for at det skal bli riktig oppbygning med …
=> Chore: bytt ut nav-frontend-grid for Verge, Fakta og Foreldelse-steg

.github/dependabot.yml, package.json, yarn.lock
Foretrekker å gruppere dependabots basert på hva som hører sammen og må/burde oppdateres sammen. Nå grupperes feks majors sammen som gjør det helt umulig å oppgradere. Vil se hvor mange PRer vi ender opp med ved å gjøre det sånn her i første omgang også kan vi evt vurdere å gruppere minors/patches hvis det blir mye. Har gjort det akkurat sånn her i ba-sak og der var det litt å jobbe seg gjennom i starten, men når man først har fått hodet over vann kommer det svært få nye oppdateringer i løpet av en uke.
=> Chore: oppdater dependabot-gruppering

src/frontend/komponenter/Fagsak/FagsakContainer.tsx, src/frontend/komponenter/Fagsak/Fakta/FaktaContainer.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Dokumentlisting/Dokumentlisting.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Historikk/Historikk.tsx, src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.tsx, src/frontend/komponenter/Felleskomponenter/PdfVisningModal/PdfVisningModal.tsx
Fant en del tilfeller av at vi har switch med default-case `return <div />`. Dette fører i disse tilfellene til at vi viser blanke elementer eller helt blanke sider, uten noen forklaring til brukeren om hvilken tilstand applikasjonen er i.
Erstatter disse med varselbokser der jeg har forsøkt å utlede hvilken `RessursStatus` vi har kommet til. Ofte `IKKE_HENTET` og iblant det eller `IKKE_TILGANG`
=> Erstatt blanke sider med varsler om hva som mangler

src/frontend/komponenter/Fagsak/BehandlingContainer.tsx, src/frontend/komponenter/Felleskomponenter/Venstremeny/sider.ts
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20488
Det er meldt inn som et ønske fra saksbehandlere om at dersom behandlingen er i steget FATTE VEDTAK, så skal saksbehandler default navigeres til faktasteget. Dette er fordi saksbehandler uansett skal starte her, for så å se gjennom hele behandlingen før eventuel godkjennelse.
PRen er delt inn i to comits: 
- Den første løser selve problemet
- Den andre er en liten refaktorering for å forenkle kode
Endringen er testet lokalt ✅
=> Besluter skal default til faktasteg

src/frontend/komponenter/Fagsak/Foreldelse/FeilutbetalingForeldelseContext.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.test.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePerioder.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/FeilutbetalingVilkårsvurderingContext.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPerioder.tsx
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20486
Når en saksbehandler åpner Foreldelse- eller Vilkårsvurderingsbildet skal følgende skje:
1. Den første ubehandledde perioden skal åpnes by default
2. Dersom alle perioder er behandlet skal den første perioden kun åpnes by default - dersom behandlingen er til totrinnskontroll.
=> Vilkårsvurdering default se periode

src/frontend/context/BehandlingContext.tsx, src/frontend/komponenter/Fagsak/BehandlingContainer.tsx, src/frontend/komponenter/Fagsak/Foreldelse/FeilutbetalingForeldelseContext.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.test.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.test.tsx, src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMelding.test.tsx, src/frontend/komponenter/Fagsak/Høyremeny/Totrinnskontroll/Totrinnskontroll.test.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/Behandlingsmeny.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/EndreBehandlendeEnhet/EndreBehandlendeEnhetContext.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/HenleggBehandling/HenleggBehandlingModal/HenleggBehandlingModal.test.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/HenleggBehandling/HenleggBehandlingModal/HenleggBehandlingModalContext.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/LeggTilFjernBrevmottakere/LeggTilFjernBrevmottakere.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/OpprettBehandling/OpprettBehandlingSkjemaContext.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/OpprettFjernVerge/OpprettFjernVerge.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/SettBehandlingTilbakeTilFakta/SettBehandlingTilbakeTilFakta.tsx, src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/hentOppdatertKravgrunnlag/HentOppdatertKravgrunnlag.tsx, src/frontend/komponenter/Fagsak/Vedtak/AvsnittSkjema.tsx, src/frontend/komponenter/Fagsak/Vedtak/FeilutbetalingVedtakContext.tsx, src/frontend/komponenter/Fagsak/Vedtak/ForhåndsvisVedtaksbrev/ForhåndsvisVedtaksbrev.tsx, src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.test.tsx, src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.tsx, src/frontend/komponenter/Fagsak/Vedtak/VedtakFritekstSkjema.tsx, src/frontend/komponenter/Fagsak/Verge/VergeContainer.test.tsx, src/frontend/komponenter/Fagsak/Verge/VergeContainer.tsx, src/frontend/komponenter/Fagsak/Verge/VergeContext.tsx, src/frontend/komponenter/Felleskomponenter/Datovelger/Datovelger.tsx, src/frontend/komponenter/Felleskomponenter/Modal/PåVent/PåVentContext.tsx, src/frontend/utils/validering.ts
Skal vise ikke-lagret-modal på vedtaksiden. Ved klikk på "lagre utkast" og "til godkjenning" og deretter godkjent validering skal man få lov til å navigere seg bort fra siden som vanlig.
Den opptrer både ved refresh og ved navigering:
=> Ferdigstill ulagret datamodal

src/frontend/index.html, src/frontend/komponenter/Felleskomponenter/Toast/Toast.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23151
Samme som disse PRene:
https://github.com/navikt/familie-ba-sak-frontend/pull/3431
https://github.com/navikt/familie-ks-sak-frontend/pull/947
Fjerner lastingen av `Source Sans Pro`, en gammel versjon av Aksel sin font `Source Sans 3`. Fjerner samtidig gammel styling som ikke blir brukt lenger (det finnes ingen `span` elementer nå i `Toast`). Vi laster inn `Source Sans 3` via [ds-css](https://github.com/navikt/aksel/blob/main/%40navikt/core/css/baseline/fonts.css), derfor trenger vi ikke laste inn egen font.
Ittno bekymringer!
_Har du husket alle punktene i listen?_
_Jeg har ikke skrevet tester fordi:_
Ikke relevant
Ingen visuelle endringer :)
=> Fjerner eksplisitt lasting av font fra google

src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMelding.tsx, src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMeldingContext.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23182
Hvis utsending av brev feiler var det før ingen visning av feilmeldingen som kommer fra requesten. Legger på visning av feilmeldingen, som ser slik ut:
Relatert til https://github.com/navikt/familie-tilbake/pull/1581
=> Legger på visning av feilmelding på utsending av brev

src/frontend/komponenter/Fagsak/Brevmottaker/BrevmottakerSkjema.tsx
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23404
Vi forhindrer valg av XU (Ukjent Land)
=> Ekskluderer XU ukjent land i brevmottaker landvelger

src/frontend/komponenter/Fagsak/Personlinje/Personlinje.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23466
Når vi kjørte en major bump av aksel-icons, var det en breaking change som vi ikke fikset. Dette fikser renamingen av et ikon som vi bruker når vi viser `Personlinje` for institusjoner.
`<Buldings3Icon />` endres til `<Buildings3Icon />`
Kilde: https://aksel.nav.no/grunnleggende/kode/migrering#194b60833d9e
=> Omgjør til riktig ikon etter major-oppgradering i aksel-icons

.gitignore, jest.config.ts, src/frontend/utils/land.ts
Denne warningen kom foran alle testene våre og er nå fikset:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
=> Fjerner warning om deprecated globals og gjør testene 10% raskere

src/backend/router.ts
Siden routeren matchet på alle URL-er ville den generere nytt CSRF token for alle requests, selv de som ikke eksisterer. Dette førte til at en request til /favicon.ico ville generere nytt CSRF token og ingen requests som er beskyttet mot CSRF ville fungere.
=> Ikke returner 200 med nytt CSRF token for sider som ikke finnes

src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainerAutoutført.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaBA.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaOS.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPerioder.test.tsx, src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPerioder.tsx
Lagt til deteksjon av når ForeslåVedtak-steget har blitt tilbakeført, som markerer vilkårsvurdering som "har ulagrede endringer" for å hindre utilsiktet navigering bort fra siden uten å lagre. Dette sikrer at brukere må håndtere konsekvensene av det tilbakeførte vedtaket før de kan gå videre i behandlingsflyten
=> Gjøre vilkårsvurdering på nytt

src/frontend/kodeverk/feilutbetalingsÅrsak.ts, src/frontend/komponenter/Fagsak/Fakta/FaktaPeriode/FaktaPeriodeSkjema.tsx, src/frontend/komponenter/Fagsak/Fakta/FeilutbetalingFaktaContext.tsx
https://github.com/user-attachments/assets/f577fb2b-177f-4360-ac63-c72f1207a8db
=> Velger automatisk hendelsesundertype uten useEffect
