src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/SplittPeriode/SplittPeriode.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/SplittPeriode/SplittPeriode.tsx
src/frontend/komponenter/Felleskomponenter/Modal/DelOppPeriode/DelOppPeriodeContext.tsx

La til validering i deltopp modal

La til validering i deltopp modal

---

README.md
src/frontend/kodeverk/feilutbetalingsÅrsak.ts

[Løser denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10354)
Avhengig av denne: https://github.com/navikt/familie-tilbake/pull/938

Skal kunne velge barn_fylt_1_år ved overgangsstønad aktivitetsplikt

---

src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.test.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/Aktsomhetsvurdering/AktsomhetsvurderingSkjema.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaBA.test.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaOS.test.tsx

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10447

Tekstendringer vilkårsvurdering "hvis forsto eller burde forstått"

---

package.json
src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx
src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/SettBehandlingPåVent/SettBehandlingPåVent.tsx
src/frontend/komponenter/Felleskomponenter/Modal/DelOppPeriode/DelOppPeriode.tsx
src/frontend/komponenter/Felleskomponenter/Modal/PåVent/PåVentModal.tsx
yarn.lock

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10742
* https://github.com/navikt/familie-felles-frontend/pull/767
Liknende som
* https://github.com/navikt/familie-ef-sak-frontend/pull/1916

Erstatt valgtDato med value i FamilieDatovelger då valgtDato er fjernet

---

.github/workflows/build.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
Dockerfile

Skal bruke node 18

---

build_n_deploy/azurerator/azure-ad-app-lokal.yaml
build_n_deploy/naiserator/naiserator_dev_gcp.yaml
src/backend/config.ts
src/backend/konfigurerApp.ts

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11924
* https://github.com/navikt/familie-tilbake/pull/1030

Erstatter dev.intern ingress med intern.dev

---

LICENSE

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-9736

Legger til MIT lisensfil

---

src/frontend/komponenter/Fagsak/Høyremeny/Menykontainer.tsx
src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMelding.test.tsx
src/frontend/komponenter/Fagsak/Høyremeny/SendMelding/SendMelding.tsx
src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/LeggTilFjernBrevmottakere/LeggTilFjernBrevmottakere.tsx
src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.tsx
src/frontend/komponenter/Felleskomponenter/Hendelsesoversikt/BrevModul/BrevmottakerListe.tsx
src/frontend/typer/behandling.ts

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-10541
Benyttet BrevmottakerListe i HøyreMeny -> SendMelding

NAV-10541 - Brevmottakere i høyre meny - under "Send brev"

---

src/frontend/komponenter/Fagsak/Brevmottaker/BrevmottakerContext.tsx

Kopierte valideringsfunksjonen til skjemafeltet "mottaker" fra ba-sak, og tilpasset den til å fungere i kombinasjon med endre-funksjonaliteten i tillegg.
Var en av checklist-oppgavene i Testoversikt-kortet: 
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12385

Passe på at endring også validerer for ulovlige mottakerkombinasjoner

---

src/frontend/kodeverk/fagsystem.ts
src/frontend/kodeverk/feilutbetalingsÅrsak.ts

Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-12710
Har lagt til det nødvendige for å få på plass tilbakekreving sak for kontantstøtte.
Flere tekster kommer senere.

Legg til nødvendige for å få på plass tilbakekreving kontantstøtte sak

---

src/frontend/kodeverk/fagsystem.ts
src/frontend/kodeverk/feilutbetalingsÅrsak.ts

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/077068028bffba85055cca2d?card=NAV-13278
Legger til kontantstøtte valg i nedtrekksmenyen

Legge til valg i nedtrekksmeny

---

src/frontend/komponenter/Fagsak/Vilkårsvurdering/FeilutbetalingVilkårsvurderingContext.tsx

Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/077068028bffba85055cca2d

Kontantstøtte skal ikke kunne ilegge renter på sammevis som barnetrygd

---

src/frontend/kodeverk/vilkårsvurdering.ts
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.test.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx

Legger til spesifikke kontantstøtte hjelptekster

Vi legger til hjelpetekst for kontantstøtte

---

package.json
yarn.lock

Ref: https://github.com/navikt/familie-tilbake-frontend/security/dependabot/15
Fjernet request, request-promise og request-promise-core

Fjernet request, request-promise og request-promise-core

---

yarn.lock

Ref: https://github.com/navikt/familie-tilbake-frontend/security/dependabot/26

Oppdatert postcss i yarn-lock

---

.snyk
package.json
yarn.lock

Fjernet snyk ettersom denne ikke lenger skal benyttes (erstattes av dependabot)

* Fjernet snyk

---

package.json
yarn.lock

+ @adobe/css-tools
+ @testing-library/jest-dom
Ref: https://github.com/yarnpkg/yarn/issues/4986#issuecomment-1500862435

Oppdatert minor @adobe/css-tools

---

src/frontend/tsconfig.json

Oppdatert tsconfig for å unngå type errors i IDEA i tester

---

package.json
yarn.lock

Bump typescript 4.9.5 => 5.3.3

Bump typescript 4=> 5

---

package.json
src/frontend/komponenter/Fagsak/Brevmottaker/Brevmottaker.tsx
src/frontend/komponenter/Fagsak/Brevmottaker/BrevmottakerContainer.tsx
src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePeriodeSkjema.tsx
src/frontend/komponenter/Fagsak/Høyremeny/Dokumentlisting/Dokumentvisning.tsx
src/frontend/komponenter/Fagsak/Høyremeny/Historikk/HistorikkInnslag.tsx
src/frontend/komponenter/Fagsak/Høyremeny/Høyremeny.tsx
src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/Behandlingsmeny.tsx
src/frontend/komponenter/Fagsak/Personlinje/Behandlingsmeny/HenleggBehandling/ForhåndsvisHenleggelsesbrev/ForhåndsvisHenleggelsesbrev.tsx
src/frontend/komponenter/Fagsak/Personlinje/Personlinje.tsx
src/frontend/komponenter/Fagsak/Vedtak/BrevmottakereAlert.tsx
src/frontend/komponenter/Fagsak/Vedtak/VedtakFritekstSkjema.tsx
src/frontend/komponenter/Felleskomponenter/Ikoner/BeslutterIkon.tsx
src/frontend/komponenter/Felleskomponenter/Ikoner/DokumentIkon.tsx
src/frontend/komponenter/Felleskomponenter/Ikoner/SaksbehandlerIkon.tsx
src/frontend/komponenter/Felleskomponenter/Ikoner/SystemIkon.tsx
src/frontend/komponenter/Felleskomponenter/TilbakeTidslinje/PeriodeController/PeriodeController.tsx
yarn.lock

* Bump @navikt/aksel-icons 4.x => 5.11.4
* Byttet ikoner fra @navikt/ds-icons => @navikt/aksel-icons
* Oppdatert størrelser der det anses relevant
_Ref:
Gamle ikoner: https://old-icons.vercel.app/
Nye ikoner: https://aksel.nav.no/ikoner_

Bump @navikt/aksel-icons og bytte ikoner fra @navikt/ds-icons til @navikt/aksel-icons

---

.github/dependabot.yml

Lagt til config for depenadbot action for github

Lagt til dependabot github actions

---

build_n_deploy/naiserator/naiserator_dev_gcp.yaml
build_n_deploy/naiserator/naiserator_prod_gcp.yaml

Fjernet ugyldig prop fra nais config (ref: nais validate)
- spec: Additional property team is not allowed

nais validate: - spec: Additional property team is not allowed

---

.github/workflows/build.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml

Bytt til GAR fra GCR.
Sammenkjørt det med KS + BA sin.

Bytt til GAR

---

.github/workflows/build_n_deploy_dev.yaml
Dockerfile
src/backend/register.ts
src/backend/server.ts

`navikt/node-express` er deprekert. Endrer til distroless
https://github.com/GoogleContainerTools/distroless/tree/main?tab=readme-ov-file

Oppdater Dockerfile til distroless

---

.github/workflows/build.yaml
.github/workflows/build_n_deploy_dev.yaml
.github/workflows/build_n_deploy_prod.yaml
Dockerfile

Validerer branchen her: https://github.com/navikt/familie-tilbake-frontend/actions/runs/8718186498

Bruk node 20. Endre til nonroot i dockerfile

---

src/frontend/context/BehandlingContext.tsx
src/frontend/hooks/useSjekklikheter.ts
src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.test.tsx
src/frontend/komponenter/Fagsak/Vedtak/VedtakContainer.tsx
src/frontend/komponenter/Felleskomponenter/ErrorBoundary/ErrorBoundary.tsx

- Laget hook for å hente sjekk-likhet-perioder fra tilbake.
- Gjør kallet/tester i VedtakContainer - resultatet skal senere knyttes til en knapp
[PR backend](https://github.com/navikt/familie-tilbake/pull/1553)

Sjekk likhet perioder

---

build_n_deploy/naiserator/naiserator_dev_gcp.yaml
build_n_deploy/naiserator/naiserator_prod_gcp.yaml
package.json
src/frontend/index.tsx
src/frontend/utils/grafanaFaro.ts
yarn.lock

Skrur på NAIS auto-instrumentation, samt bruker Grafana Faro for å samle inn telemetri. I vårt tilfelle: metrikker og tracing-data.
https://docs.nais.io/observability/how-to/auto-instrumentation/
https://docs.nais.io/observability/frontend/

Legg til auto-instrumentation + grafana faro

---

LICENSE
README.md
assets/error.html
package.json
src/frontend/index.html
src/frontend/kodeverk/vilkårsvurdering.ts
src/frontend/komponenter/Felleskomponenter/Dashboard.tsx
src/frontend/komponenter/Felleskomponenter/FTHeader/FTHeader.tsx
src/frontend/typer/enhet.ts

NAV->Nav og fjerner familie i tittel

---

README.md

Lettere status for diverse miljøer

Badge for workflows for forskjellige miljøer

---

src/frontend/komponenter/Fagsak/Fakta/FaktaContainer.test.tsx
src/frontend/komponenter/Fagsak/Fakta/FaktaSkjema.tsx
src/frontend/komponenter/Fagsak/Foreldelse/ForeldelseContainer.test.tsx
src/frontend/komponenter/Fagsak/Foreldelse/ForeldelsePeriode/FeilutbetalingForeldelsePerioder.tsx
src/frontend/komponenter/Fagsak/Verge/VergeContainer.test.tsx
src/frontend/komponenter/Fagsak/Verge/VergeContainer.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingContainer.test.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPerioder.tsx

https://trello.com/c/DoLTZ6Py/49-endre-navn-p%C3%A5-knapp-n%C3%A5r-saksbehandler-lagrer-i-trinn-vilk%C3%A5rsvurdering

Byttet til lagre istedenfor bekreft

---

package.json
pnpm-lock.yaml

Hvorfor: @sillerud  https://github.com/navikt/familie-tilbake-frontend/actions/runs/14188743150/job/39828568878

Går tilbake til express 4.21.2

---

src/frontend/utils/validering.ts

Non breaking space er nå tillat

Kalkulator innliming: nbsp er tillatt i tekster

---

src/frontend/api/http/HttpProvider.tsx
src/frontend/typer/feilutbetalingtyper.ts
src/frontend/typer/vedtakTyper.ts

For å korte ned kompileringstiden: https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections

Bytter til interface-intersection

---

src/frontend/komponenter/Felleskomponenter/Skjemaelementer/LabelMedSpråk.tsx

La til et lite mellomrom mellom Label og språkkode

---

src/backend/config.ts

for å unngå feil i brukerlenke variabelnavn

Typedefinerer enviroment config

---

src/frontend/kodeverk/vilkårsvurdering.ts
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjema.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaBA.test.tsx
src/frontend/komponenter/Fagsak/Vilkårsvurdering/VilkårsvurderingPeriode/VilkårsvurderingPeriodeSkjemaOS.test.tsx

Erstatter tooltips med inline tekst

---

src/jest-setup.ts

TextEncoder fungerer ikke for nyeste patching av TS
https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest

Polyfill TextEncoder

---

src/frontend/komponenter/App.tsx
src/frontend/komponenter/Container.tsx
src/frontend/komponenter/Fagsak/BehandlingContainer.tsx
src/frontend/komponenter/Felleskomponenter/FeilInnlasting/FeilInnlasting.tsx
src/frontend/pages/feilsider/Feilside.tsx

Hey developer

---

src/backend/config.ts
src/frontend/context/FagsakContext.tsx
src/frontend/komponenter/Fagsak/FagsakContainer.tsx
src/frontend/komponenter/Fagsak/Personlinje/Personlinje.tsx
src/frontend/komponenter/Felleskomponenter/FTHeader/FTHeader.tsx
src/frontend/store/fagsak.ts

Flytter saksoversikt og fjerner revurderingslenke

---

src/frontend/komponenter/Fagsak/Fakta/FaktaContainer.test.tsx
src/frontend/komponenter/Fagsak/Fakta/FaktaContainer.tsx
src/frontend/komponenter/Fagsak/Fakta/FaktaPeriode/FaktaPerioder.tsx
src/frontend/komponenter/Fagsak/Fakta/FaktaPeriode/historikk/HistoriskFaktaVisning.tsx
src/frontend/komponenter/Fagsak/Fakta/FaktaSkjema.tsx
src/frontend/komponenter/Fagsak/Høyremeny/Totrinnskontroll/Totrinnskontroll.test.tsx
src/frontend/typer/behandling.ts

Endrer faktasteg titler
